site_name: Nova Developer Manual
nav:
  - Home: index.md
  - Introduction:
      Domains: intro/domains.md
      Repositories: intro/repos.md
      Migrating Repositories: intro/repo-migration.md
  - Backend:
      Deployment Procedures(Backend):
        Prerequisites: backend/deployment/prerequisites.md
        Deployment: backend/deployment/deployment.md
        Post Deploy Setup: backend/deployment/post-deploy.md
        FAQs: backend/deployment/faqs.md
      Introduction to the Serverless Framework: backend/serverless-intro.md
      Introduction to the Nova Codebase(Backend): backend/codebase-intro.md
      Data Deep Dive:
        DynamoDB Basics: backend/deepdive/dynamo-basics.md

use_directory_urls: false

site_author: Li Gangwei, Louis Lor
site_dir: public
site_url: https://nova35.gitlab.io/novaweb/v2/developer-manual

markdown_extensions:
  - attr_list
