site_name: Nova Developer Manual
nav:
  - Home: index.md
  - Introduction:
      Domains: intro/domains.md
      Repositories: intro/repos.md
  - Deployment Procedures(Backend):
      Prerequisites: deployment/prerequisites.md
      Deployment: deployment/deployment.md
      FAQs: deployment/faqs.md

use_directory_urls: false

site_author: Li Gangwei, Louis Lor
site_dir: public
site_url: https://nova35.gitlab.io/developer-manual

markdown_extensions:
  - attr_list
