site_name: Nova Documentation
nav:
  - Home: index.md
  - Introduction:
      Domains: intro/domains.md
      Repositories: intro/repos.md

use_directory_urls: false

site_author: Li Gangwei
theme: ivory

markdown_extensions:
  - attr_list
