site_name: Nova Documentation
nav:
  - Home: index.md
  - Introduction:
      Domains: intro/domains.md
      Repositories: intro/repos.md
  - Deployment Procedures(Backend):
      Prerequisites: deployment/prerequisites.md
      Deployment: deployment/deployment.md

use_directory_urls: false

site_author: Li Gangwei

markdown_extensions:
  - attr_list
